# NUMPY 

So lets have a basic exercise on numpy. 

In [2]:
import numpy as np 

#### create an array of 10 tens 

In [6]:
# your code here-
arr = np.array([10,10,10,10,10,10,10,10,10,10])
print(arr)

[10 10 10 10 10 10 10 10 10 10]


#### Create an array of all the odd integers from 100 to 200

In [10]:
# your code here-
arr = np.arange(100,200)
for i in range(len(arr)):
    if (arr[i] % 2 == 1):
        print(arr[i], end = "  ")


101  103  105  107  109  111  113  115  117  119  121  123  125  127  129  131  133  135  137  139  141  143  145  147  149  151  153  155  157  159  161  163  165  167  169  171  173  175  177  179  181  183  185  187  189  191  193  195  197  199  

#### Create a 3x3 identity matrix

In [11]:
# your code here-
arr=np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### write a code that gives the output given below
 ** *Note! In order to not lose the output, make sure you don't code in the cell that is directly above the plot, there is an extra cell above that one which won't overwrite that plot!* **



In [34]:
# your code here-
arr = np.arange(1,26).reshape(5, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Create a 4X4 matrix with values starting from 0

In [35]:
# your code here-
arr = np.arange(0,16).reshape(4, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### Use NumPy to generate an array of 9 random numbers sampled from a standard normal distribution

In [43]:
# your code here-
randarr = np.random.normal(size=9)
print(randarr)

[-0.11451598 -0.4123279  -0.06902393 -0.07341693 -1.03782994  0.50125583
  0.55647834 -1.01508694  0.75689934]


In [45]:
j=np.arange(12,24).reshape(3,4)
j

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### on the given above array 'j' , perform the given questions. 

#### 1. Get the standard deviation of the values in mat

In [46]:
# your code here-
np.std(j)

3.452052529534663

#### 2. Get the sum of all the columns in mat

In [49]:
# your code here-
column_sum = j.sum(axis=0)
print(column_sum)

[48 51 54 57]


#### 3. write a code that gives the following output given below.
** *Note! In order to not lose the output, make sure you don't code in the cell that is directly above the plot, there is an extra cell above that one which won't overwrite that plot!* **

In [53]:
j[:, [1]]

array([[13],
       [17],
       [21]])

In [17]:
# your code here-


array([[13],
       [17],
       [21]])

#### 4. Get the sum of all the values in mat

In [58]:
# your code here-
print("Sum of all elements of matrix j:", np.sum(j))

Sum of all elements of matrix j: 210


# GLAD YOU COMPLETED THIS PART, GOOD LUCK AHEAD!!